kind: PersistentVolume
apiVersion: v1
metadata:
  name: pyflowops-pv
  namespace: local  # Sets Namespace
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # total capacity for this persistent volume
  accessModes:
    - ReadWriteOnce
  hostPath: # where pesistent volume is created on the kubernetes node (needs to be /data for minikube)
    path: "/data/pyflowops" # path on the host machine
