apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - namespace.yaml # This namespace is completed in the pfo CLI
- dashboard-ingressroute.yaml
- dashboard-stripprefix-middleware.yaml
