# Helm chart values for Traefik
# Use non-privileged ports to avoid needing root
ports:
  web:
    port: 30080
    nodePort: 30080 # Non-privileged port for HTTP
    expose:
      default: true
  websecure:
    port: 30443
    nodePort: 30443 # Non-privileged port for HTTPS
    expose:
      default: true
    tls:
      enabled: true

# Configure the Traefik service as a LoadBalancer
service:
  type: NodePort # Use NodePort for local development -- LoadBalancer for production
  enabled: true
  # This tells Traefik to request an IP from MetalLB
  annotations:
    metallb.universe.tf/address-pool: pyflowops-ip-pool # Updated to match your IPAddressPool name

  nodePorts:
    web: 30080
    websecure: 30443 # HTTPS traffic on non-privileged port

# Enable the Kubernetes Ingress provider
providers:
  kubernetesIngress:
    enabled: true
    # Watch all namespaces for Ingress resources
    namespaces: []
  kubernetesCRD:
    enabled: true # Enable Kubernetes CRD provider for IngressRoutes
    watch: true # Disable watching for CRDs to avoid conflicts with IngressRoutes
    pollInterval: 30s # Polling interval for CRDs

# Force the Traefik pod to run on the control-plane node where the ports are mapped
controller:
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Equal
      effect: NoSchedule
  additionalArguments:
    - "--entrypoints.web.address=:30080"
    - "--entrypoints.websecure.address=:30443"
    - "--entrypoints.websecure.tls=true"
    - "--api.dashboard=true"
    - "--api.insecure=true"
    - "--api.debug=true" # Enable debug mode for Traefik API

# Optional: Enable and expose the Traefik Dashboard (useful for debugging)
# IMPORTANT: Do not expose the dashboard publicly in production environments
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
    matchRule: Host(`traefik.pyflowops.local`)
    tls: {}

persistence:
  enabled: false

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
