# traefik-values.yaml
# Helm chart values for Traefik

# Use non-privileged ports to avoid needing root
ports:
  web:
    port: 30080      # HTTP traffic on non-privileged port
    hostPort: 30080  # Expose on node port 8000
  websecure:
    port: 30443      # HTTPS traffic on non-privileged port
    hostPort: 30443  # Expose on node port 8443
    tls:
      enabled: true
  traefik:
    port: 30080      # Dashboard/API

# Enable the Kubernetes Ingress provider
providers:
  kubernetesIngress:
    enabled: true
    # Watch all namespaces for Ingress resources
    namespaces: []
  kubernetesCRD:
    enabled: true # Enable Kubernetes CRD provider for IngressRoutes
    watch: false # Disable watching for CRDs to avoid conflicts with IngressRoutes
    pollInterval: 30s # Polling interval for CRDs

# Configure the Traefik service as a LoadBalancer
service:
  enabled: true
  type: LoadBalancer
  # This tells Traefik to request an IP from MetalLB
  annotations:
    metallb.universe.tf/address-pool: pyflowops-ip-pool # Updated to match your IPAddressPool name

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.pyflowops.local`)
    tls: {}

persistence:
  enabled: false

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
