# my-traefik-values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
        http:
          tls: {}
    api:
      dashboard: true
    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
    log:
      level: INFO
---
# Helm chart values to integrate with the above ConfigMap
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

# Enable and configure the dashboard IngressRoute
ingressRoute:
  dashboard:
    enabled: true
    # For local testing, you might use a hostname like dashboard.localhost
    # For production, you'll need a real domain and potentially a CertificateResolver
    matchRule: "Host(`traefik.pyflowops.com`)" 
    entryPoints: ["websecure"] # Expose dashboard over HTTPS
    tls: {} # Enable TLS for the dashboard

# Configure Traefik service (type LoadBalancer recommended for external access)
service:
  type: LoadBalancer
  annotations: {} # Add cloud-provider specific annotations if needed for LoadBalancer
  
# Persistence for ACME (Let's Encrypt) certificates
persistence:
  enabled: true
  storageClassName: standard # Replace with your storage class
  accessMode: ReadWriteOnce
  size: 1Gi

# Configure certificatesResolvers for Let's Encrypt
certificatesResolvers:
  le:
    acme:
      email: philip.delorenzol@gmail.com # **IMPORTANT: Change this to your email**
      storage: traefik-acme.json
      # Choose one of the following challenges:
      # httpChallenge:
      #   entryPoint: web
      tlsChallenge: {}
      # dnsChallenge:
      #   provider: cloudflare # Example provider
      #   delayBeforeCheck: 0
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"
