apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ cookiecutter.namespace }}-storage
  namespace: {{ cookiecutter.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
