apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - network/
#- rabbitmq
#- nginx/
resources:
#- redis/
- storage/
#- postgres/
- storage-class.yaml
- namespace.yaml

images:
- name: documentation:local
  newName: documentation
  newTag: local
#- name: unitytree-qa:k8s-local
#  newName: unitytree-qa
#  newTag: k8s-local
#- name: unitytree-uiux:k8s-local
#  newName: ut-dev-tools
#  newTag: k8s-local
#- name: ut-dev-tools:k8s-local
#  newName: ut-dev-tools
#  newTag: k8s-local
