apiVersion: v1
kind: Secret
metadata:
  name: pyflowops-github-ssh-key # A unique name for your secret
  namespace: argocd              # The namespace where ArgoCD is installed (usually 'argocd')
  labels:
    argocd.argoproj.io/secret-type: repo-creds # This label tells ArgoCD to discover this secret as a repository credential
stringData: # Use stringData for easier handling of multi-line strings like private keys
  # The type of repository. For SSH, it's 'git'.
  type: git
  # The URL of your private Git repository in SSH format.
  # Example: git@github.com:your-org/your-repo.git
  # Or: ssh://git@your-git-server.com/path/to/repo.git
  url: git@github.com:PyFlowOps/documentation.git # REPLACE with your actual SSH repository URL
  # Your SSH private key. It must be in a format supported by OpenSSH (e.g., RSA, ED25519).
  # Ensure proper indentation for the multi-line string.
  # Replace '-----BEGIN OPENSSH PRIVATE KEY----- ... -----END OPENSSH PRIVATE KEY-----'
  # with your actual private key content.
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDb+D...
    ... (Your actual private key lines here) ...
    -----END OPENSSH PRIVATE KEY-----
  # Optional: To skip host key verification (NOT RECOMMENDED for production)
  # insecureIgnoreHostKey: "true" # Uncomment if you need to ignore host key verification
