apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argdocd-server-ingress
  namespace: argocd
  annotations:
    # This annotation tells Kubernetes that Traefik should handle this Ingress
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: argocd.pyflowops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  #tls:
  #- hosts:
  #  - argocd.pyflowops.local
  #  secretName: argocd-tls-secret # You can create a self-signed cert or disable TLS for now
