apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: documentation
  namespace: argocd # Or the namespace where your ArgoCD instance is installed
spec:
  project: pyflowops # The ArgoCD Project this application belongs to
  destination:
    namespace: local # The target namespace in your Kubernetes cluster
    server: https://kubernetes.default.svc # The Kubernetes API server URL (usually the in-cluster default)
  source:
    repoURL: git@github.com:pyflowops/documentation.git
    path: manifests/argocd/overlays # This tells ArgoCD to look in the 'k8s/production' directory
    targetRevision: main # Track the 'main' branch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
