apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - namespace.yaml # This namespace is completed in the pfo CLI
- argocd-app-project.yaml
- argocd-ssh-secret.yaml
- argocd-app-pfo-documentation.yaml
- argocd-config.yaml
#- argocd-ingress.yaml
- argocd-traefik-ingressroute.yaml
