apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-app-project.yaml
- argocd-ssl-certs.yaml
- argocd-config.yaml
- argocd-middleware.yaml
- argocd-traefik-ingressroute.yaml
