apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: documentation
  namespace: argocd  # ArgoCD namespace
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=ghcr.io/pyflowops/documentation
    argocd-image-updater.argoproj.io/myapp.update-strategy: local
spec:
  project: pyflowops
  source:
    repoURL: https://github.com/pyflowops/documentation.git
    targetRevision: HEAD
    path: k8s  # Path to your manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: local  # kind cluster namespace for pfo applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
